import type { FormField, FieldType } from './types';

type TemplateField = Omit<Partial<FormField>, 'id'> & { type: FieldType; label: string };

export type FormTemplate = {
  id: string;
  icon: string;
  name: string;
  description: string;
  category: string;
  accentColor: string;
  fields: TemplateField[];
};

export type TemplateCategory = {
  id: string;
  icon: string;
  label: string;
  templates: FormTemplate[];
};

// ─── Templates ────────────────────────────────────────────────────────────────

export const TEMPLATE_CATEGORIES: TemplateCategory[] = [
  {
    id: 'business',
    icon: '💼',
    label: 'Business',
    templates: [
      {
        id: 'contact-us',
        icon: '📩',
        name: 'Contact Us',
        description: 'Simple inquiry form with name, email, subject and message.',
        category: 'business',
        accentColor: '#60a5fa',
        fields: [
          { type: 'text',     label: 'Full Name',     placeholder: 'Your full name',         required: true,  fieldWidth: 'half' },
          { type: 'email',    label: 'Email Address', placeholder: 'you@example.com',        required: true,  fieldWidth: 'half' },
          { type: 'phone',    label: 'Phone Number',  placeholder: '+91 00000 00000',        required: false, fieldWidth: 'half' },
          { type: 'text',     label: 'Company / Organisation', placeholder: 'Where do you work?', required: false, fieldWidth: 'half' },
          { type: 'select',   label: 'Subject',       required: true, fieldWidth: 'full',
            options: ['General Enquiry', 'Sales', 'Technical Support', 'Billing', 'Partnership', 'Other'] },
          { type: 'textarea', label: 'Message',       placeholder: 'Describe your enquiry in detail...', required: true, minLength: 20 },
          { type: 'checkbox', label: 'I agree to be contacted by your team regarding this enquiry', required: true },
        ] as TemplateField[],
      },
      {
        id: 'job-application',
        icon: '🧑‍💼',
        name: 'Job Application',
        description: 'Full hiring form with personal info, skills, experience and documents.',
        category: 'business',
        accentColor: '#34d399',
        fields: [
          { type: 'section',  label: 'Personal Information', sectionColor: '#34d399', sectionDescription: 'Basic applicant details' },
          { type: 'text',     label: 'Full Name',            placeholder: 'As per government ID', required: true,  fieldWidth: 'half' },
          { type: 'email',    label: 'Email Address',        placeholder: 'you@example.com',      required: true,  fieldWidth: 'half' },
          { type: 'phone',    label: 'Phone Number',         placeholder: '+91 00000 00000',       required: true,  fieldWidth: 'half' },
          { type: 'date',     label: 'Date of Birth',                                              required: false, fieldWidth: 'half' },
          { type: 'section',  label: 'Role & Experience',    sectionColor: '#10b981', sectionDescription: 'Position you are applying for' },
          { type: 'text',     label: 'Position Applied For', placeholder: 'e.g. Senior Frontend Developer', required: true,  fieldWidth: 'half' },
          { type: 'select',   label: 'Department',           required: true,  fieldWidth: 'half',
            options: ['Engineering', 'Design', 'Marketing', 'Sales', 'Operations', 'HR', 'Finance', 'Other'] },
          { type: 'select',   label: 'Total Experience',     required: true,  fieldWidth: 'half',
            options: ['Fresher (0–1 yr)', '1–3 years', '3–5 years', '5–8 years', '8–12 years', '12+ years'] },
          { type: 'currency', label: 'Current CTC',          placeholder: '0.00', prefix: '₹',   required: false, fieldWidth: 'half' },
          { type: 'currency', label: 'Expected CTC',         placeholder: '0.00', prefix: '₹',   required: true,  fieldWidth: 'half' },
          { type: 'text',     label: 'Notice Period',        placeholder: 'e.g. 30 days / Immediate', required: true, fieldWidth: 'half' },
          { type: 'section',  label: 'Skills & Background',  sectionColor: '#059669', sectionDescription: 'Tell us more about your expertise' },
          { type: 'textarea', label: 'Key Skills',           placeholder: 'List your top technical and soft skills...', required: true },
          { type: 'url',      label: 'LinkedIn Profile',     placeholder: 'https://linkedin.com/in/…', required: false, fieldWidth: 'half' },
          { type: 'url',      label: 'Portfolio / GitHub',   placeholder: 'https://github.com/…',      required: false, fieldWidth: 'half' },
          { type: 'file',     label: 'Resume / CV',                                                required: true  },
          { type: 'textarea', label: 'Cover Letter / Why Us?', placeholder: 'Why are you interested in this role?', required: false },
        ] as TemplateField[],
      },
      {
        id: 'customer-feedback',
        icon: '⭐',
        name: 'Customer Feedback',
        description: 'Post-purchase or service review with ratings and comments.',
        category: 'business',
        accentColor: '#fbbf24',
        fields: [
          { type: 'text',     label: 'Your Name',             placeholder: 'Optional — leave blank to stay anonymous', required: false, fieldWidth: 'half' },
          { type: 'email',    label: 'Email Address',         placeholder: 'For follow-up (optional)',                 required: false, fieldWidth: 'half' },
          { type: 'select',   label: 'Product / Service',     required: true, fieldWidth: 'full',
            options: ['Product A', 'Product B', 'Service Plan', 'Support Experience', 'Onboarding', 'Other'] },
          { type: 'rating',   label: 'Overall Satisfaction',  required: true, min: 1, max: 5,  fieldWidth: 'half' },
          { type: 'rating',   label: 'Ease of Use',           required: true, min: 1, max: 5,  fieldWidth: 'half' },
          { type: 'rating',   label: 'Value for Money',       required: true, min: 1, max: 5,  fieldWidth: 'half' },
          { type: 'rating',   label: 'Customer Support',      required: false, min: 1, max: 5, fieldWidth: 'half' },
          { type: 'radio',    label: 'Would you recommend us?', required: true,
            options: ['Definitely Yes', 'Probably Yes', 'Not Sure', 'Probably Not', 'Definitely Not'] },
          { type: 'textarea', label: 'What did we do well?',  placeholder: 'Highlight the positives...', required: false },
          { type: 'textarea', label: 'What can we improve?',  placeholder: 'Be specific — we read every response!', required: false },
          { type: 'range',    label: 'Net Promoter Score (NPS)', min: 0, max: 10,              required: true },
        ] as TemplateField[],
      },
      {
        id: 'event-registration',
        icon: '🎟️',
        name: 'Event Registration',
        description: 'Collect attendee info, meal preferences, and session choices.',
        category: 'business',
        accentColor: '#a78bfa',
        fields: [
          { type: 'section',  label: 'Attendee Details',     sectionColor: '#a78bfa', sectionDescription: 'Who is attending?' },
          { type: 'text',     label: 'Full Name',            placeholder: 'As it should appear on badge', required: true,  fieldWidth: 'half' },
          { type: 'email',    label: 'Email Address',        placeholder: 'Confirmation will be sent here', required: true,  fieldWidth: 'half' },
          { type: 'phone',    label: 'Phone Number',         placeholder: '+91 00000 00000',               required: true,  fieldWidth: 'half' },
          { type: 'text',     label: 'Organisation / Company', placeholder: 'Your employer or institution', required: false, fieldWidth: 'half' },
          { type: 'select',   label: 'Ticket Type',          required: true, fieldWidth: 'half',
            options: ['Early Bird', 'Standard', 'VIP', 'Group (5+)', 'Student', 'Complimentary'] },
          { type: 'number',   label: 'Number of Seats',      placeholder: '1', required: true, min: 1, max: 20, fieldWidth: 'half' },
          { type: 'section',  label: 'Preferences',          sectionColor: '#7c3aed', sectionDescription: 'Help us serve you better' },
          { type: 'radio',    label: 'Meal Preference',      required: true,
            options: ['Vegetarian', 'Vegan', 'Non-Vegetarian', 'Jain', 'No Preference'] },
          { type: 'checkbox', label: 'Accessibility requirements?', required: false, fieldWidth: 'half' },
          { type: 'checkbox', label: 'Interested in networking session?', required: false, fieldWidth: 'half' },
          { type: 'textarea', label: 'Special Requests',     placeholder: 'Dietary restrictions, accessibility needs, etc.', required: false },
        ] as TemplateField[],
      },
      {
        id: 'vendor-onboarding',
        icon: '🤝',
        name: 'Vendor Onboarding',
        description: 'Supplier registration with business details, documents and compliance.',
        category: 'business',
        accentColor: '#f97316',
        fields: [
          { type: 'section',  label: 'Business Details',       sectionColor: '#f97316', sectionDescription: 'Company / supplier information' },
          { type: 'text',     label: 'Business / Company Name', placeholder: 'Registered legal name', required: true,  fieldWidth: 'half' },
          { type: 'select',   label: 'Business Type',           required: true, fieldWidth: 'half',
            options: ['Sole Proprietor', 'Partnership', 'Private Limited', 'Public Limited', 'LLP', 'NGO/Trust'] },
          { type: 'email',    label: 'Business Email',          placeholder: 'contact@company.com', required: true,  fieldWidth: 'half' },
          { type: 'phone',    label: 'Business Phone',          placeholder: '+91 00000 00000',     required: true,  fieldWidth: 'half' },
          { type: 'url',      label: 'Website',                 placeholder: 'https://company.com', required: false, fieldWidth: 'half' },
          { type: 'text',     label: 'Years in Business',       placeholder: 'e.g. 5',              required: false, fieldWidth: 'half' },
          { type: 'section',  label: 'Compliance & Tax',        sectionColor: '#ea580c', sectionDescription: 'Regulatory information' },
          { type: 'text',     label: 'PAN Number',   placeholder: 'e.g. ABCDE1234F', required: true,  maxLength: 10, validationPreset: 'pan', fieldWidth: 'half' },
          { type: 'text',     label: 'GST Number',   placeholder: 'e.g. 22AAAAA0000A1Z5', required: false, maxLength: 15, validationPreset: 'gst', fieldWidth: 'half' },
          { type: 'section',  label: 'Bank Details',            sectionColor: '#c2410c', sectionDescription: 'Payment details for invoices' },
          { type: 'text',     label: 'Bank Name',    placeholder: 'e.g. HDFC Bank', required: true, fieldWidth: 'half' },
          { type: 'text',     label: 'Account Number', placeholder: 'Enter account number', required: true, validationPreset: 'numbers-only', fieldWidth: 'half' },
          { type: 'text',     label: 'IFSC Code',    placeholder: 'e.g. HDFC0001234', required: true, maxLength: 11, validationPreset: 'ifsc', fieldWidth: 'half' },
          { type: 'file',     label: 'GST Certificate / Business Registration Document', required: false },
          { type: 'checkbox', label: 'I confirm all details provided are accurate and complete', required: true },
        ] as TemplateField[],
      },
    ],
  },
  {
    id: 'hr',
    icon: '🧑‍🤝‍🧑',
    label: 'HR & People',
    templates: [
      {
        id: 'employee-onboarding',
        icon: '🪪',
        name: 'Employee Onboarding',
        description: 'New hire form covering personal, tax, bank and emergency details.',
        category: 'hr',
        accentColor: '#38bdf8',
        fields: [
          { type: 'section',  label: 'Personal Details',     sectionColor: '#38bdf8', sectionDescription: 'Basic information about the new employee' },
          { type: 'text',     label: 'Full Name',            placeholder: 'As per Aadhaar / passport', required: true,  fieldWidth: 'half' },
          { type: 'email',    label: 'Personal Email',       placeholder: 'personal@example.com',     required: true,  fieldWidth: 'half' },
          { type: 'phone',    label: 'Mobile Number',        placeholder: '+91 00000 00000',          required: true,  fieldWidth: 'half' },
          { type: 'date',     label: 'Date of Birth',                                                  required: true,  fieldWidth: 'half' },
          { type: 'select',   label: 'Gender',               required: false, fieldWidth: 'half',
            options: ['Male', 'Female', 'Non-Binary', 'Prefer Not to Say'] },
          { type: 'select',   label: 'Blood Group',          required: false, fieldWidth: 'half',
            options: ['A+', 'A−', 'B+', 'B−', 'O+', 'O−', 'AB+', 'AB−', 'Unknown'] },
          { type: 'section',  label: 'Job Details',          sectionColor: '#0284c7', sectionDescription: 'Role and department' },
          { type: 'text',     label: 'Employee ID',          placeholder: 'Assigned by HR',          required: false, fieldWidth: 'half' },
          { type: 'text',     label: 'Designation',          placeholder: 'e.g. Software Engineer',  required: true,  fieldWidth: 'half' },
          { type: 'text',     label: 'Department',           placeholder: 'e.g. Engineering',        required: true,  fieldWidth: 'half' },
          { type: 'date',     label: 'Date of Joining',                                               required: true,  fieldWidth: 'half' },
          { type: 'section',  label: 'Government IDs',       sectionColor: '#0369a1', sectionDescription: 'For payroll and compliance' },
          { type: 'text',     label: 'Aadhaar Number',       placeholder: 'XXXX XXXX XXXX',          required: true,  maxLength: 14, fieldWidth: 'half' },
          { type: 'text',     label: 'PAN Number',           placeholder: 'e.g. ABCDE1234F',         required: true,  maxLength: 10, validationPreset: 'pan', fieldWidth: 'half' },
          { type: 'text',     label: 'PF UAN Number',        placeholder: 'Universal Account Number', required: false, fieldWidth: 'half' },
          { type: 'text',     label: 'ESI Number',           placeholder: 'Employee State Insurance', required: false, fieldWidth: 'half' },
          { type: 'section',  label: 'Emergency Contact',    sectionColor: '#dc2626', sectionDescription: 'Who to reach in case of emergency' },
          { type: 'text',     label: 'Emergency Contact Name',     placeholder: 'Full name',        required: true,  fieldWidth: 'half', validationPreset: 'letters-only' },
          { type: 'text',     label: 'Relationship',               placeholder: 'e.g. Spouse',     required: true,  fieldWidth: 'half' },
          { type: 'phone',    label: 'Emergency Phone',            placeholder: '+91 00000 00000',  required: true,  fieldWidth: 'half' },
        ] as TemplateField[],
      },
      {
        id: 'leave-request',
        icon: '🏖️',
        name: 'Leave Request',
        description: 'Employee leave application with dates, type and reason.',
        category: 'hr',
        accentColor: '#86efac',
        fields: [
          { type: 'text',     label: 'Employee Name',   placeholder: 'Your full name',   required: true,  fieldWidth: 'half' },
          { type: 'text',     label: 'Employee ID',     placeholder: 'e.g. EMP-001',     required: true,  fieldWidth: 'half' },
          { type: 'text',     label: 'Department',      placeholder: 'Your department',  required: true,  fieldWidth: 'half' },
          { type: 'text',     label: 'Reporting Manager', placeholder: 'Manager name',   required: true,  fieldWidth: 'half' },
          { type: 'select',   label: 'Leave Type',      required: true, fieldWidth: 'half',
            options: ['Casual Leave', 'Sick Leave', 'Earned/PL', 'Maternity/Paternity', 'Compensatory Off', 'Unpaid Leave', 'Other'] },
          { type: 'number',   label: 'No. of Days',     placeholder: '1', min: 0.5, max: 90, required: true, fieldWidth: 'half' },
          { type: 'date',     label: 'From Date',       required: true,  fieldWidth: 'half' },
          { type: 'date',     label: 'To Date',         required: true,  fieldWidth: 'half' },
          { type: 'textarea', label: 'Reason for Leave', placeholder: 'Briefly explain your reason...', required: true },
          { type: 'text',     label: 'Contact During Leave', placeholder: 'Phone or email reachable during leave', required: false },
          { type: 'checkbox', label: 'I confirm work handover has been arranged', required: true },
        ] as TemplateField[],
      },
      {
        id: 'performance-review',
        icon: '📊',
        name: 'Performance Review',
        description: 'Annual or quarterly appraisal with self-assessment and goals.',
        category: 'hr',
        accentColor: '#c4b5fd',
        fields: [
          { type: 'section',  label: 'Employee Info',       sectionColor: '#c4b5fd', sectionDescription: 'Review period details' },
          { type: 'text',     label: 'Employee Name',       placeholder: 'Full name',         required: true,  fieldWidth: 'half' },
          { type: 'text',     label: 'Employee ID',         placeholder: 'e.g. EMP-001',      required: true,  fieldWidth: 'half' },
          { type: 'text',     label: 'Designation',         placeholder: 'Current role',      required: true,  fieldWidth: 'half' },
          { type: 'select',   label: 'Review Period',       required: true, fieldWidth: 'half',
            options: ['Q1 (Jan–Mar)', 'Q2 (Apr–Jun)', 'Q3 (Jul–Sep)', 'Q4 (Oct–Dec)', 'Annual (Full Year)'] },
          { type: 'section',  label: 'Self Assessment',     sectionColor: '#7c3aed', sectionDescription: 'Rate your own performance' },
          { type: 'rating',   label: 'Goal Achievement',    required: true, min: 1, max: 5, fieldWidth: 'half' },
          { type: 'rating',   label: 'Quality of Work',     required: true, min: 1, max: 5, fieldWidth: 'half' },
          { type: 'rating',   label: 'Teamwork',            required: true, min: 1, max: 5, fieldWidth: 'half' },
          { type: 'rating',   label: 'Communication',       required: true, min: 1, max: 5, fieldWidth: 'half' },
          { type: 'rating',   label: 'Initiative & Innovation', required: true, min: 1, max: 5, fieldWidth: 'half' },
          { type: 'rating',   label: 'Time Management',     required: true, min: 1, max: 5, fieldWidth: 'half' },
          { type: 'textarea', label: 'Key Achievements This Period', placeholder: 'Describe your top 3 accomplishments...', required: true },
          { type: 'textarea', label: 'Challenges Faced',              placeholder: 'What obstacles did you encounter?',    required: false },
          { type: 'textarea', label: 'Goals for Next Period',         placeholder: 'Set 3–5 measurable goals...',           required: true },
          { type: 'textarea', label: 'Training / Development Needs',  placeholder: 'Skills or courses you want to pursue', required: false },
        ] as TemplateField[],
      },
    ],
  },
  {
    id: 'education',
    icon: '🎓',
    label: 'Education',
    templates: [
      {
        id: 'student-registration',
        icon: '📚',
        name: 'Student Registration',
        description: 'Course enrollment with academic background and documents.',
        category: 'education',
        accentColor: '#67e8f9',
        fields: [
          { type: 'section',  label: 'Personal Details',   sectionColor: '#67e8f9', sectionDescription: 'Student information' },
          { type: 'text',     label: 'Full Name',          placeholder: 'As per school records', required: true,  fieldWidth: 'half' },
          { type: 'email',    label: 'Email Address',      placeholder: 'student@example.com',   required: true,  fieldWidth: 'half' },
          { type: 'phone',    label: 'Phone Number',       placeholder: '+91 00000 00000',       required: true,  fieldWidth: 'half' },
          { type: 'date',     label: 'Date of Birth',                                             required: true,  fieldWidth: 'half' },
          { type: 'select',   label: 'Gender',             required: false, fieldWidth: 'half',
            options: ['Male', 'Female', 'Non-Binary', 'Prefer Not to Say'] },
          { type: 'text',     label: 'Nationality',        placeholder: 'e.g. Indian',           required: false, fieldWidth: 'half' },
          { type: 'section',  label: 'Academic Details',   sectionColor: '#0891b2', sectionDescription: 'Course and qualification' },
          { type: 'text',     label: 'Course / Programme', placeholder: 'e.g. B.Tech CSE',      required: true,  fieldWidth: 'half' },
          { type: 'select',   label: 'Year / Semester',    required: true, fieldWidth: 'half',
            options: ['1st Year', '2nd Year', '3rd Year', '4th Year', '5th Year', 'PG 1st Year', 'PG 2nd Year'] },
          { type: 'text',     label: 'Previous School / College', placeholder: 'Last attended institution', required: true, fieldWidth: 'half' },
          { type: 'number',   label: 'Previous Percentage / CGPA', placeholder: 'e.g. 85.5', min: 0, max: 100, required: true, fieldWidth: 'half' },
          { type: 'file',     label: 'Mark Sheet / Transcript', required: true },
          { type: 'file',     label: 'ID Proof (Aadhaar / Passport)', required: true },
          { type: 'text',     label: 'Guardian / Parent Name', placeholder: 'Full name', required: true, fieldWidth: 'half' },
          { type: 'phone',    label: 'Guardian Phone',         placeholder: '+91 00000 00000', required: true, fieldWidth: 'half' },
        ] as TemplateField[],
      },
      {
        id: 'quiz-survey',
        icon: '📝',
        name: 'Quiz / Survey',
        description: 'General purpose quiz template with MCQs, ratings and open questions.',
        category: 'education',
        accentColor: '#fde68a',
        fields: [
          { type: 'text',     label: 'Your Name',           placeholder: 'Full name',      required: true,  fieldWidth: 'half' },
          { type: 'text',     label: 'Roll Number / ID',    placeholder: 'e.g. 21CS001',   required: false, fieldWidth: 'half' },
          { type: 'select',   label: 'Class / Section',     required: false, fieldWidth: 'half',
            options: ['Class 9A', 'Class 9B', 'Class 10A', 'Class 10B', 'Class 11', 'Class 12', 'Other'] },
          { type: 'date',     label: 'Date',                required: true, fieldWidth: 'half' },
          { type: 'section',  label: 'Questions',           sectionColor: '#d97706', sectionDescription: 'Answer all questions honestly' },
          { type: 'radio',    label: 'Question 1: What is the capital of France?', required: true,
            options: ['London', 'Berlin', 'Paris', 'Rome'] },
          { type: 'radio',    label: 'Question 2: Which planet is closest to the Sun?', required: true,
            options: ['Earth', 'Venus', 'Mercury', 'Mars'] },
          { type: 'textarea', label: 'Question 3: Explain the water cycle in your own words.', placeholder: 'Write your answer here...', required: true },
          { type: 'rating',   label: 'How would you rate the difficulty of this quiz?', required: true, min: 1, max: 5 },
          { type: 'textarea', label: 'Any feedback for your teacher?', placeholder: 'Optional comments...', required: false },
        ] as TemplateField[],
      },
    ],
  },
  {
    id: 'health',
    icon: '🏥',
    label: 'Health & Medical',
    templates: [
      {
        id: 'patient-intake',
        icon: '🩺',
        name: 'Patient Intake',
        description: 'New patient registration with vitals, history and insurance info.',
        category: 'health',
        accentColor: '#f87171',
        fields: [
          { type: 'section',  label: 'Patient Information',  sectionColor: '#f87171', sectionDescription: 'Basic details' },
          { type: 'text',     label: 'Full Name',             placeholder: 'Patient full name',    required: true,  fieldWidth: 'half' },
          { type: 'date',     label: 'Date of Birth',                                               required: true,  fieldWidth: 'half' },
          { type: 'select',   label: 'Gender',                required: true, fieldWidth: 'half',
            options: ['Male', 'Female', 'Other', 'Prefer Not to Say'] },
          { type: 'select',   label: 'Blood Group',           required: false, fieldWidth: 'half',
            options: ['A+', 'A−', 'B+', 'B−', 'O+', 'O−', 'AB+', 'AB−', 'Unknown'] },
          { type: 'phone',    label: 'Phone Number',          placeholder: '+91 00000 00000',      required: true,  fieldWidth: 'half' },
          { type: 'email',    label: 'Email Address',         placeholder: 'For reports (optional)', required: false, fieldWidth: 'half' },
          { type: 'section',  label: 'Vitals',                sectionColor: '#dc2626', sectionDescription: 'Current measurements' },
          { type: 'number',   label: 'Height (cm)',           placeholder: 'e.g. 170', min: 50, max: 250, required: false, fieldWidth: 'half' },
          { type: 'number',   label: 'Weight (kg)',           placeholder: 'e.g. 70',  min: 1,  max: 300, required: false, fieldWidth: 'half' },
          { type: 'text',     label: 'Blood Pressure',        placeholder: 'e.g. 120/80 mmHg',    required: false, fieldWidth: 'half' },
          { type: 'number',   label: 'Pulse Rate (bpm)',      placeholder: 'e.g. 72', min: 30, max: 200, required: false, fieldWidth: 'half' },
          { type: 'section',  label: 'Medical History',       sectionColor: '#b91c1c', sectionDescription: 'Previous conditions' },
          { type: 'textarea', label: 'Known Allergies',       placeholder: 'Food, medications, environmental...', required: false },
          { type: 'textarea', label: 'Current Medications',   placeholder: 'Name, dosage, frequency',             required: false },
          { type: 'textarea', label: 'Chief Complaint / Reason for Visit', placeholder: 'Describe your symptoms...', required: true },
          { type: 'text',     label: 'Emergency Contact Name',  placeholder: 'Full name',         required: true,  fieldWidth: 'half' },
          { type: 'phone',    label: 'Emergency Contact Phone', placeholder: '+91 00000 00000',   required: true,  fieldWidth: 'half' },
        ] as TemplateField[],
      },
      {
        id: 'appointment-booking',
        icon: '📅',
        name: 'Appointment Booking',
        description: 'Doctor / clinic appointment request with preferred slots.',
        category: 'health',
        accentColor: '#6ee7b7',
        fields: [
          { type: 'text',     label: 'Patient Name',          placeholder: 'Full name',        required: true,  fieldWidth: 'half' },
          { type: 'phone',    label: 'Phone Number',          placeholder: '+91 00000 00000',  required: true,  fieldWidth: 'half' },
          { type: 'email',    label: 'Email Address',         placeholder: 'For confirmation', required: false, fieldWidth: 'half' },
          { type: 'date',     label: 'Date of Birth',                                           required: false, fieldWidth: 'half' },
          { type: 'select',   label: 'Department / Speciality', required: true, fieldWidth: 'half',
            options: ['General Medicine', 'Cardiology', 'Orthopaedics', 'Neurology', 'Dermatology', 'Gynaecology', 'Paediatrics', 'ENT', 'Other'] },
          { type: 'select',   label: 'Preferred Date',        required: true, fieldWidth: 'half',
            options: ['As soon as possible', 'Within 3 days', 'Within a week', 'Flexible'] },
          { type: 'radio',    label: 'Preferred Time Slot',   required: true,
            options: ['Morning (9am–12pm)', 'Afternoon (12pm–4pm)', 'Evening (4pm–7pm)'] },
          { type: 'select',   label: 'Visit Type',            required: true, fieldWidth: 'half',
            options: ['First Consultation', 'Follow-up', 'Emergency', 'Second Opinion'] },
          { type: 'textarea', label: 'Chief Complaint / Symptoms', placeholder: 'Briefly describe your concern...', required: true },
          { type: 'checkbox', label: 'I consent to the clinic contacting me via phone/email', required: true },
        ] as TemplateField[],
      },
    ],
  },
  {
    id: 'ecommerce',
    icon: '🛒',
    label: 'E-Commerce',
    templates: [
      {
        id: 'order-form',
        icon: '📦',
        name: 'Order Form',
        description: 'Product order with quantity, size, delivery address and payment method.',
        category: 'ecommerce',
        accentColor: '#fb923c',
        fields: [
          { type: 'section',  label: 'Customer Details',     sectionColor: '#fb923c', sectionDescription: 'Who is placing the order?' },
          { type: 'text',     label: 'Full Name',            placeholder: 'Delivery name',            required: true,  fieldWidth: 'half' },
          { type: 'email',    label: 'Email Address',        placeholder: 'Order confirmation email',  required: true,  fieldWidth: 'half' },
          { type: 'phone',    label: 'Phone Number',         placeholder: 'For delivery updates',      required: true,  fieldWidth: 'full' },
          { type: 'section',  label: 'Order Details',        sectionColor: '#ea580c', sectionDescription: 'What are you ordering?' },
          { type: 'text',     label: 'Product Name / SKU',   placeholder: 'e.g. Blue T-Shirt XL',     required: true,  fieldWidth: 'half' },
          { type: 'number',   label: 'Quantity',             placeholder: '1', min: 1, max: 999,       required: true,  fieldWidth: 'half' },
          { type: 'select',   label: 'Size / Variant',       required: false, fieldWidth: 'half',
            options: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'N/A'] },
          { type: 'select',   label: 'Colour',               required: false, fieldWidth: 'half',
            options: ['Red', 'Blue', 'Green', 'Black', 'White', 'Other'] },
          { type: 'currency', label: 'Unit Price',           placeholder: '0.00', prefix: '₹',        required: false, fieldWidth: 'half' },
          { type: 'select',   label: 'Payment Method',       required: true, fieldWidth: 'half',
            options: ['UPI', 'Credit Card', 'Debit Card', 'Net Banking', 'Cash on Delivery', 'Wallet'] },
          { type: 'section',  label: 'Delivery Address',     sectionColor: '#c2410c', sectionDescription: 'Where to ship?' },
          { type: 'textarea', label: 'Address',              placeholder: 'House No., Street, Area, Landmark', required: true },
          { type: 'text',     label: 'City',                 placeholder: 'City',      required: true,  fieldWidth: 'half', validationPreset: 'letters-only' },
          { type: 'text',     label: 'PIN Code',             placeholder: '6-digit PIN', required: true,  fieldWidth: 'half', maxLength: 6, validationPreset: 'pincode' },
          { type: 'textarea', label: 'Special Instructions', placeholder: 'Gift wrapping, fragile item, delivery slot, etc.', required: false },
        ] as TemplateField[],
      },
      {
        id: 'return-refund',
        icon: '↩️',
        name: 'Return / Refund',
        description: 'Request return or refund with order details and reason.',
        category: 'ecommerce',
        accentColor: '#fca5a5',
        fields: [
          { type: 'text',     label: 'Full Name',            placeholder: 'Your name',               required: true,  fieldWidth: 'half' },
          { type: 'email',    label: 'Email Address',        placeholder: 'Used during order',        required: true,  fieldWidth: 'half' },
          { type: 'phone',    label: 'Phone Number',         placeholder: '+91 00000 00000',          required: true,  fieldWidth: 'half' },
          { type: 'text',     label: 'Order ID',             placeholder: 'e.g. ORD-20240521-001',    required: true,  fieldWidth: 'half' },
          { type: 'text',     label: 'Product Name',         placeholder: 'Item to return',           required: true,  fieldWidth: 'half' },
          { type: 'date',     label: 'Order Date',                                                     required: true,  fieldWidth: 'half' },
          { type: 'select',   label: 'Return Reason',        required: true, fieldWidth: 'full',
            options: ['Wrong Item Received', 'Item Damaged / Defective', 'Item Not as Described', 'Size/Fit Issue', 'No Longer Needed', 'Other'] },
          { type: 'radio',    label: 'Resolution Preferred', required: true,
            options: ['Refund to Original Payment Method', 'Store Credit / Wallet', 'Exchange for Different Item'] },
          { type: 'textarea', label: 'Describe the Issue',   placeholder: 'Please provide as much detail as possible...', required: true },
          { type: 'file',     label: 'Upload Photo (if damaged / wrong item)', required: false },
        ] as TemplateField[],
      },
    ],
  },
  {
    id: 'survey',
    icon: '📊',
    label: 'Research & Surveys',
    templates: [
      {
        id: 'nps-survey',
        icon: '📈',
        name: 'NPS Survey',
        description: 'Net Promoter Score survey to measure customer loyalty.',
        category: 'survey',
        accentColor: '#34d399',
        fields: [
          { type: 'text',     label: 'Your Name',            placeholder: 'Optional',               required: false, fieldWidth: 'half' },
          { type: 'email',    label: 'Email Address',        placeholder: 'Optional',               required: false, fieldWidth: 'half' },
          { type: 'range',    label: 'How likely are you to recommend us to a friend or colleague? (0 = Not at all, 10 = Extremely likely)', min: 0, max: 10, required: true },
          { type: 'radio',    label: 'Which best describes your relationship with us?', required: false,
            options: ['Customer', 'Partner', 'Employee', 'Prospect', 'Other'] },
          { type: 'textarea', label: 'What is the main reason for your score?', placeholder: 'Be as specific as possible...', required: false },
          { type: 'textarea', label: 'What can we do to improve your experience?', placeholder: 'Your feedback helps us grow...', required: false },
          { type: 'rating',   label: 'Overall Satisfaction', required: true, min: 1, max: 5 },
        ] as TemplateField[],
      },
      {
        id: 'market-research',
        icon: '🔍',
        name: 'Market Research',
        description: 'Consumer preference and buying behaviour survey.',
        category: 'survey',
        accentColor: '#818cf8',
        fields: [
          { type: 'section',  label: 'Demographics',         sectionColor: '#818cf8', sectionDescription: 'Tell us a little about yourself' },
          { type: 'select',   label: 'Age Group',            required: true, fieldWidth: 'half',
            options: ['Under 18', '18–24', '25–34', '35–44', '45–54', '55–64', '65+'] },
          { type: 'select',   label: 'Gender',               required: false, fieldWidth: 'half',
            options: ['Male', 'Female', 'Non-Binary', 'Prefer Not to Say'] },
          { type: 'select',   label: 'Location',             required: false, fieldWidth: 'half',
            options: ['Metro City', 'Tier 2 City', 'Town', 'Rural', 'Other'] },
          { type: 'select',   label: 'Monthly Income',       required: false, fieldWidth: 'half',
            options: ['Under ₹25k', '₹25k–50k', '₹50k–1L', '₹1L–2L', 'Above ₹2L', 'Prefer Not to Say'] },
          { type: 'section',  label: 'Buying Behaviour',     sectionColor: '#6366f1', sectionDescription: 'Your purchasing habits' },
          { type: 'select',   label: 'How often do you purchase online?', required: true, fieldWidth: 'half',
            options: ['Daily', 'Weekly', 'Monthly', 'Occasionally', 'Rarely / Never'] },
          { type: 'radio',    label: 'What influences your purchase decision most?', required: true,
            options: ['Price', 'Brand Trust', 'Reviews & Ratings', 'Features', 'Recommendation from Friends', 'Advertisements'] },
          { type: 'checkbox', label: 'Which platforms do you shop on? (Select all that apply)', required: false,
            options: ['Amazon', 'Flipkart', 'Myntra', 'Meesho', 'Blinkit / Zepto', 'Brand Website', 'Other'] },
          { type: 'rating',   label: 'How satisfied are you with online shopping overall?', required: true, min: 1, max: 5 },
          { type: 'textarea', label: 'What improvements would you like to see in e-commerce?', placeholder: 'Your candid feedback...', required: false },
        ] as TemplateField[],
      },
    ],
  },
];

export const ALL_TEMPLATES: FormTemplate[] = TEMPLATE_CATEGORIES.flatMap(c => c.templates);
