// ── Experience 2: Globe — country data ────────────────────────────────────

export type Country = {
  id: string;
  name: string;
  emoji: string;
  continent: string;
  capital: string;
  color: string;
  bgGradient: string;
  accentColor: string;
  glowColor: string;
  currency: string;
  currencySymbol: string;
  tagline: string;
  lore: string;
  // SVG approximate position on the globe map (% of container)
  x: number;
  y: number;
  // Cinematic panels shown when you enter this country
  cinematic: { title: string; text: string; icon: string }[];
  // Suggested field preset for this country's locale
  fieldPreset: 'india' | 'usa' | 'uk' | 'japan' | 'germany' | 'brazil' | 'uae' | 'australia' | 'china' | 'france' | 'canada' | 'south-africa';
};

export const COUNTRIES: Country[] = [
  {
    id: 'india',
    name: 'India',
    emoji: '🇮🇳',
    continent: 'Asia',
    capital: 'New Delhi',
    color: '#ff9933',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #ff9933 0%, #138808 40%, #000080 100%)',
    accentColor: '#ff9933',
    glowColor: 'rgba(255,153,51,0.35)',
    currency: 'Indian Rupee',
    currencySymbol: '₹',
    tagline: 'Where Every Form Tells a Billion Stories',
    lore: 'From the Himalayas to the Indian Ocean — 1.4 billion perspectives, one form to capture them all.',
    x: 63, y: 42,
    cinematic: [
      { icon: '🕌', title: 'Land of Wonders', text: 'Seven thousand years of civilisation. Mathematics. Zero. Chess. All born here.' },
      { icon: '🌶️', title: 'Spice Routes', text: 'Merchants crossed deserts and oceans just for a pinch of what grows on these hills.' },
      { icon: '📋', title: 'Your Mission', text: 'Build forms for a billion users. Include PAN, GST, IFSC, Aadhaar — every detail matters.' },
    ],
    fieldPreset: 'india',
  },
  {
    id: 'usa',
    name: 'United States',
    emoji: '🇺🇸',
    continent: 'North America',
    capital: 'Washington D.C.',
    color: '#3c3b6e',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #b22234 0%, #3c3b6e 50%, #001f5b 100%)',
    accentColor: '#b22234',
    glowColor: 'rgba(178,34,52,0.35)',
    currency: 'US Dollar',
    currencySymbol: '$',
    tagline: 'Land of the Free Form',
    lore: 'Where Silicon Valley was built on forms, feedback loops, and first-mover advantage.',
    x: 20, y: 35,
    cinematic: [
      { icon: '🗽', title: 'The New World', text: 'Three hundred million voices. Every survey, every census, every NPS score.' },
      { icon: '💻', title: 'Silicon Dreams', text: 'The startup culture that turned a textarea into a unicorn. Forms power everything.' },
      { icon: '📋', title: 'Your Mission', text: 'Build enterprise-grade forms with SSN validation, ZIP codes, and state selectors.' },
    ],
    fieldPreset: 'usa',
  },
  {
    id: 'uk',
    name: 'United Kingdom',
    emoji: '🇬🇧',
    continent: 'Europe',
    capital: 'London',
    color: '#012169',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #c8102e 0%, #012169 55%, #001040 100%)',
    accentColor: '#c8102e',
    glowColor: 'rgba(200,16,46,0.35)',
    currency: 'British Pound',
    currencySymbol: '£',
    tagline: 'Forms Fit for the Crown',
    lore: 'From the Magna Carta to GDPR — Britain has always had strong opinions about paperwork.',
    x: 44, y: 25,
    cinematic: [
      { icon: '👑', title: 'The Kingdom', text: 'Where bureaucracy was perfected over eight centuries. Every form is a parliamentary act.' },
      { icon: '🏛️', title: 'The Empire of Data', text: 'The National Archives hold 1000 years of records. Your form joins the legacy.' },
      { icon: '📋', title: 'Your Mission', text: 'GDPR-compliant forms with postcode lookup, NI numbers, and British English labels.' },
    ],
    fieldPreset: 'uk',
  },
  {
    id: 'japan',
    name: 'Japan',
    emoji: '🇯🇵',
    continent: 'Asia',
    capital: 'Tokyo',
    color: '#bc002d',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #bc002d 0%, #1a0008 60%, #000000 100%)',
    accentColor: '#bc002d',
    glowColor: 'rgba(188,0,45,0.35)',
    currency: 'Japanese Yen',
    currencySymbol: '¥',
    tagline: 'Precision. Perfection. Form.',
    lore: 'The nation that invented kaizen — continuous improvement. Every field on your form is a ritual.',
    x: 80, y: 35,
    cinematic: [
      { icon: '⛩️', title: 'Land of the Rising Sun', text: 'Where attention to detail is a spiritual practice. A misaligned checkbox is a dishonour.' },
      { icon: '🌸', title: 'Sakura Season', text: 'Fleeting beauty. A form is temporary — but the data it captures, eternal.' },
      { icon: '📋', title: 'Your Mission', text: 'Build ultra-precise forms with postal codes, hiragana fields, and Japanese date formats.' },
    ],
    fieldPreset: 'japan',
  },
  {
    id: 'germany',
    name: 'Germany',
    emoji: '🇩🇪',
    continent: 'Europe',
    capital: 'Berlin',
    color: '#000000',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #ffcc00 0%, #dd0000 50%, #000000 100%)',
    accentColor: '#ffcc00',
    glowColor: 'rgba(255,204,0,0.35)',
    currency: 'Euro',
    currencySymbol: '€',
    tagline: 'Engineered. Not Designed.',
    lore: 'The country that built the Autobahn, the printing press, and the strictest privacy laws in Europe.',
    x: 48, y: 26,
    cinematic: [
      { icon: '⚙️', title: 'Das Precision', text: 'Gutenberg invented the printing press here. Every form you build honours that legacy.' },
      { icon: '🏎️', title: 'Engineering Excellence', text: 'No speed limits on forms either. Build fast, validate hard, ship clean.' },
      { icon: '📋', title: 'Your Mission', text: 'DSGVO-compliant forms with PLZ codes, IBAN validation, and German precision.' },
    ],
    fieldPreset: 'germany',
  },
  {
    id: 'brazil',
    name: 'Brazil',
    emoji: '🇧🇷',
    continent: 'South America',
    capital: 'Brasília',
    color: '#009c3b',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #009c3b 0%, #fedf00 50%, #002776 100%)',
    accentColor: '#fedf00',
    glowColor: 'rgba(254,223,0,0.35)',
    currency: 'Brazilian Real',
    currencySymbol: 'R$',
    tagline: 'O Maior Formulário do Mundo',
    lore: 'Amazon basin. Carnival energy. The world\'s largest tropical nation collects data with passion.',
    x: 28, y: 60,
    cinematic: [
      { icon: '🌊', title: 'Amazon Depths', text: 'The most biodiverse nation on Earth. Your form captures stories from 210 million people.' },
      { icon: '🎊', title: 'Carnival Spirit', text: 'Every response is a celebration. Brazil fills forms with the energy of samba.' },
      { icon: '📋', title: 'Your Mission', text: 'Build Brazilian forms with CPF validation, CEP codes, and Portuguese field labels.' },
    ],
    fieldPreset: 'brazil',
  },
  {
    id: 'uae',
    name: 'UAE',
    emoji: '🇦🇪',
    continent: 'Middle East',
    capital: 'Abu Dhabi',
    color: '#00732f',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #00732f 0%, #ffffff 40%, #ff0000 70%, #000000 100%)',
    accentColor: '#c8a200',
    glowColor: 'rgba(200,162,0,0.35)',
    currency: 'UAE Dirham',
    currencySymbol: 'د.إ',
    tagline: 'Where Vision Meets Velocity',
    lore: 'From desert to skyscraper in 50 years. The UAE doesn\'t wait — it builds tomorrow today.',
    x: 58, y: 42,
    cinematic: [
      { icon: '🏙️', title: 'City of Gold', text: 'Dubai\'s skyline changed every year for 30 years. So did its data requirements.' },
      { icon: '✈️', title: 'Hub of the World', text: 'More nationalities than any city on Earth. Your form must speak every language.' },
      { icon: '📋', title: 'Your Mission', text: 'Multi-language forms with Emirates ID, trade licence, and visa number fields.' },
    ],
    fieldPreset: 'uae',
  },
  {
    id: 'australia',
    name: 'Australia',
    emoji: '🇦🇺',
    continent: 'Oceania',
    capital: 'Canberra',
    color: '#00008b',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #00008b 0%, #cc0000 50%, #003300 100%)',
    accentColor: '#ffcc00',
    glowColor: 'rgba(255,204,0,0.3)',
    currency: 'Australian Dollar',
    currencySymbol: 'A$',
    tagline: 'G\'day, Form Builder',
    lore: 'The land down under — where even the dangerous wildlife fills out forms before attacking.',
    x: 78, y: 68,
    cinematic: [
      { icon: '🦘', title: 'The Great Southern Land', text: 'Oldest living culture on Earth. 65,000 years of storytelling. Now it\'s your form\'s turn.' },
      { icon: '🐨', title: 'No Worries', text: 'Australians invented the preference for simplicity. Short forms. Clear labels. Done.' },
      { icon: '📋', title: 'Your Mission', text: 'Build Aussie forms with TFN validation, Medicare numbers, and BSB bank codes.' },
    ],
    fieldPreset: 'australia',
  },
  {
    id: 'china',
    name: 'China',
    emoji: '🇨🇳',
    continent: 'Asia',
    capital: 'Beijing',
    color: '#de2910',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #de2910 0%, #8b0000 55%, #1a0000 100%)',
    accentColor: '#ffde00',
    glowColor: 'rgba(255,222,0,0.35)',
    currency: 'Chinese Yuan',
    currencySymbol: '¥',
    tagline: '一个表单，十四亿个故事',
    lore: 'The world\'s largest digital economy. WeChat has more daily forms than most countries have people.',
    x: 74, y: 36,
    cinematic: [
      { icon: '🐉', title: 'Dragon\'s Domain', text: 'Five thousand years of writing systems. Your form inherits the world\'s oldest tradition.' },
      { icon: '🧱', title: 'The Great Firewall', text: 'China moved fast. The infrastructure that handles 1.4 billion users daily starts with a form.' },
      { icon: '📋', title: 'Your Mission', text: 'Build forms with Chinese ID numbers, 邮政编码 postal codes, and WeChat integration hooks.' },
    ],
    fieldPreset: 'china',
  },
  {
    id: 'france',
    name: 'France',
    emoji: '🇫🇷',
    continent: 'Europe',
    capital: 'Paris',
    color: '#002395',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #002395 0%, #ffffff 50%, #ed2939 100%)',
    accentColor: '#ed2939',
    glowColor: 'rgba(237,41,57,0.35)',
    currency: 'Euro',
    currencySymbol: '€',
    tagline: 'L\'Art du Formulaire',
    lore: 'The Enlightenment. The Revolution. The concept of human rights. All started with someone writing things down.',
    x: 45, y: 28,
    cinematic: [
      { icon: '🗼', title: 'Liberté', text: 'The French declared human rights in 1789. They\'ve been documenting them in forms ever since.' },
      { icon: '🍷', title: 'Art de Vivre', text: 'A form should be beautiful. Clear. Elegant. Like French cuisine — every field has its purpose.' },
      { icon: '📋', title: 'Your Mission', text: 'RGPD-compliant forms with INSEE codes, SIRET numbers, and Parisian elegance.' },
    ],
    fieldPreset: 'france',
  },
  {
    id: 'canada',
    name: 'Canada',
    emoji: '🇨🇦',
    continent: 'North America',
    capital: 'Ottawa',
    color: '#ff0000',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #ff0000 0%, #ffffff 50%, #ff0000 100%)',
    accentColor: '#ff0000',
    glowColor: 'rgba(255,0,0,0.3)',
    currency: 'Canadian Dollar',
    currencySymbol: 'C$',
    tagline: 'Sorry, We Made Your Form Polite',
    lore: 'The most apologetic nation on Earth. Their forms say "Please" and "Thank you" twice.',
    x: 18, y: 22,
    cinematic: [
      { icon: '🍁', title: 'The Great White North', text: 'Maple syrup, hockey, and some of the world\'s most polite data collection practices.' },
      { icon: '🏔️', title: 'Rocky Mountain Data', text: 'From the Atlantic to the Pacific — the second-largest country needs bilingual forms.' },
      { icon: '📋', title: 'Your Mission', text: 'Bilingual EN/FR forms with SIN validation, Canadian postal codes, and HST numbers.' },
    ],
    fieldPreset: 'canada',
  },
  {
    id: 'south-africa',
    name: 'South Africa',
    emoji: '🇿🇦',
    continent: 'Africa',
    capital: 'Pretoria',
    color: '#007a4d',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #007a4d 0%, #ffb612 45%, #de3831 75%, #002395 100%)',
    accentColor: '#ffb612',
    glowColor: 'rgba(255,182,18,0.35)',
    currency: 'South African Rand',
    currencySymbol: 'R',
    tagline: 'Ubuntu: A Form is a Person Through People',
    lore: 'The Rainbow Nation. 11 official languages. One form to unite them all.',
    x: 52, y: 70,
    cinematic: [
      { icon: '🌈', title: 'Rainbow Nation', text: '11 official languages. The most linguistically diverse forms on the continent.' },
      { icon: '💎', title: 'Diamonds and Data', text: 'The most industrialised economy in Africa. Your form serves a continent rising.' },
      { icon: '📋', title: 'Your Mission', text: 'Build forms with SA ID numbers, VAT registration, and Ubuntu-friendly design.' },
    ],
    fieldPreset: 'south-africa',
  },
];

export const CONTINENTS = [
  { id: 'all',           name: 'All',           emoji: '🌍' },
  { id: 'Asia',          name: 'Asia',           emoji: '🌏' },
  { id: 'Europe',        name: 'Europe',         emoji: '🌍' },
  { id: 'North America', name: 'North America',  emoji: '🌎' },
  { id: 'South America', name: 'South America',  emoji: '🌎' },
  { id: 'Africa',        name: 'Africa',         emoji: '🌍' },
  { id: 'Middle East',   name: 'Middle East',    emoji: '🌍' },
  { id: 'Oceania',       name: 'Oceania',        emoji: '🌏' },
];
