import { Avatar, WorldTheme, FieldType, FormField, ValidationPreset } from './types';

export const AVATARS: Avatar[] = [
  {
    id: 'guy',
    name: 'Guy Dangerous',
    title: 'The Cursed Pioneer',
    emoji: '🏃',
    color: '#ff8c00',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #cc5500 0%, #7a1500 45%, #120300 100%)',
    description: 'He stole the idol. He woke the curse. The demons he unleashed will chase him across every world — and he\'s completely fine with that. This is his race to win.',
    trait: 'BALANCED',
    ability: 'Idol Sense',
    abilityIcon: '🔮',
    speed: 8,
    power: 8,
    agility: 8,
  },
  {
    id: 'scarlett',
    name: 'Scarlett Fox',
    title: 'The Ghost Runner',
    emoji: '🦊',
    color: '#ff3355',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #cc1133 0%, #660011 45%, #140005 100%)',
    description: 'Scientists documented three separate Scarletts during her last realm sprint — all moving simultaneously. None were caught. She leaves afterimages, not apologies.',
    trait: 'FASTEST',
    ability: 'Afterburn Trail',
    abilityIcon: '💨',
    speed: 10,
    power: 4,
    agility: 10,
  },
  {
    id: 'barry',
    name: 'Barry Bones',
    title: 'The Revenant',
    emoji: '💀',
    color: '#b39ddb',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #7c4dff 0%, #1a0050 45%, #050012 100%)',
    description: 'Death tried him once — and lost the paperwork. He clawed out of the catacombs three days later: undead, furious, and significantly more dangerous than before.',
    trait: 'STRONGEST',
    ability: 'Undying Rage',
    abilityIcon: '☠️',
    speed: 5,
    power: 10,
    agility: 7,
  },
  {
    id: 'karma',
    name: 'Karma Lee',
    title: 'The Chi Empress',
    emoji: '🐉',
    color: '#00e676',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #00c853 0%, #00591a 45%, #001208 100%)',
    description: 'Trained for 40 years in a temple deeper than this one. She doesn\'t run from the demons — she runs because she has chosen to. The distinction matters more than you think.',
    trait: 'MOST AGILE',
    ability: 'Chi Flow',
    abilityIcon: '🌀',
    speed: 7,
    power: 8,
    agility: 10,
  },
  {
    id: 'montana',
    name: 'Montana Smith',
    title: 'The Iron Relic Hunter',
    emoji: '🪖',
    color: '#ffd740',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #ffab00 0%, #5d3f00 45%, #1a1200 100%)',
    description: 'Seventeen forbidden vaults. Five continents. One basilisk. His maps list places that don\'t officially exist. His whip is carved from a spine that was never meant to be a whip.',
    trait: 'MOST POWERFUL',
    ability: 'Relic Mastery',
    abilityIcon: '🗺️',
    speed: 6,
    power: 10,
    agility: 6,
  },
  {
    id: 'francisco',
    name: 'Francisco Montoya',
    title: 'The Blade Saint',
    emoji: '⚔️',
    color: '#40c4ff',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #0288d1 0%, #00215a 45%, #000812 100%)',
    description: 'His blades predate the temple. He has fought in six continents and two dimensions. When Francisco enters a room, demons quietly calculate the fastest exit route.',
    trait: 'ELITE WARRIOR',
    ability: 'Twin Blade Strike',
    abilityIcon: '🗡️',
    speed: 8,
    power: 10,
    agility: 6,
  },
  {
    id: 'zack',
    name: 'Zack Wonder',
    title: 'The Slam Dunk Legend',
    emoji: '🏀',
    color: '#ff6d00',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #ff6d00 0%, #7c2a00 45%, #1a0900 100%)',
    description: 'Three-time world champion. Retired at 28 because every league ran out of challenges. The temple was the first obstacle that made him break a sweat. He enjoys it.',
    trait: 'EXPLOSIVE',
    ability: 'Slam Dunk Leap',
    abilityIcon: '🏀',
    speed: 10,
    power: 7,
    agility: 9,
  },
  {
    id: 'aria',
    name: 'Aria Jones',
    title: 'The Shadow Dancer',
    emoji: '🌙',
    color: '#ce93d8',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #9c27b0 0%, #2d0045 45%, #0a0015 100%)',
    description: 'She was never in the room. She was never not in the room. Nobody agrees on which. The temple\'s motion detectors logged zero entries. She has been here three times.',
    trait: 'STEALTHIEST',
    ability: 'Shadow Phase',
    abilityIcon: '🌑',
    speed: 9,
    power: 5,
    agility: 10,
  },
  {
    id: 'coco',
    name: 'Coco Montoya',
    title: 'The Jungle Queen',
    emoji: '🌺',
    color: '#ff4081',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #c2185b 0%, #560022 45%, #150008 100%)',
    description: 'The jungle told her the temple\'s every secret before she set foot inside it. Animals part for her. Trees lean. The demons hesitated — and that hesitation cost them everything.',
    trait: 'NATURE BOND',
    ability: 'Wild Command',
    abilityIcon: '🦁',
    speed: 8,
    power: 8,
    agility: 8,
  },
  {
    id: 'rex',
    name: 'Rex Hunter',
    title: 'The Beast Sovereign',
    emoji: '🦁',
    color: '#ffca28',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #f9a825 0%, #5d4000 45%, #160e00 100%)',
    description: 'Raised by something larger than a lion and older than the temple. He communicates in growls that other runners can\'t hear. The demons interpret them as threats. Correctly.',
    trait: 'BERSERKER',
    ability: 'Primal Roar',
    abilityIcon: '🔱',
    speed: 7,
    power: 10,
    agility: 7,
  },
  {
    id: 'nova',
    name: 'Nova Storm',
    title: 'The Lightning Sovereign',
    emoji: '⚡',
    color: '#e8f5e9',
    bgGradient: 'radial-gradient(ellipse at 50% 0%, #b2dfdb 0%, #004d40 45%, #00100d 100%)',
    description: 'She is not running. She is selecting which moment in time to occupy. Physics has filed several complaints. They have all been dismissed.',
    trait: 'TRANSCENDENT',
    ability: 'Time Slip',
    abilityIcon: '🌀',
    speed: 10,
    power: 6,
    agility: 10,
  },
];

export const WORLDS: WorldTheme[] = [
  {
    id: 'jungle',
    name: 'Jungle World',
    emoji: '🌴',
    description: 'The cursed idol was stolen here. Ancient demon guardians now hunt every corridor of these crumbling vine-choked ruins — and they\'re gaining on you.',
    tagline: 'WHERE LEGENDS BEGIN',
    primaryColor: '#1a5c1a',
    secondaryColor: '#2d8a2d',
    accentColor: '#ffd700',
    textColor: '#f0e8d0',
    mutedColor: '#a8c88a',
    bg: 'radial-gradient(ellipse at 30% 20%, #1a4a0a 0%, #0d1f0d 50%, #050a04 100%)',
    cardBg: 'rgba(8, 22, 8, 0.92)',
    borderColor: '#3d8a3d',
    buttonGradient: 'linear-gradient(135deg, #5c2800 0%, #8B4513 35%, #cd853f 70%, #ffd700 100%)',
    buttonText: '#0d0500',
    inputBg: 'rgba(10, 30, 8, 0.9)',
    particles: ['🌿', '🍃', '🦋', '🌺', '🐦', '✨', '🌳', '🐆'],
    glowColor: '#5ab55a',
  },
  {
    id: 'snow',
    name: 'Snow World',
    emoji: '❄️',
    description: 'The blizzard erases your tracks — and theirs. Ice-encased temples hold secrets older than the frost itself. One slip and the abyss claims you.',
    tagline: 'FROZEN IN TIME',
    primaryColor: '#4a90d9',
    secondaryColor: '#87ceeb',
    accentColor: '#a8d8ff',
    textColor: '#e8f4ff',
    mutedColor: '#b8d4e8',
    bg: 'radial-gradient(ellipse at 50% 0%, #1a3a6e 0%, #0a1a2e 55%, #030a18 100%)',
    cardBg: 'rgba(8, 22, 50, 0.94)',
    borderColor: '#4a80c8',
    buttonGradient: 'linear-gradient(135deg, #0a3a6e 0%, #1a6ba3 40%, #4a90d9 75%, #a8d8ff 100%)',
    buttonText: '#030a18',
    inputBg: 'rgba(8, 28, 58, 0.92)',
    particles: ['❄️', '⛄', '🌨️', '💎', '🔷', '✨', '🧊', '☃️'],
    glowColor: '#6aaee8',
  },
  {
    id: 'desert',
    name: 'Desert World',
    emoji: '🏜️',
    description: 'Pharaoh\'s curse turns the sands against you. Dunes shift and swallow all who linger. The heat isn\'t the danger — the ancient mummies rising from below are.',
    tagline: 'SANDS OF ETERNITY',
    primaryColor: '#c8922a',
    secondaryColor: '#e8b860',
    accentColor: '#ffb830',
    textColor: '#fef0d0',
    mutedColor: '#d4a870',
    bg: 'radial-gradient(ellipse at 50% 100%, #8b3800 0%, #4a1800 40%, #1a0800 100%)',
    cardBg: 'rgba(35, 12, 0, 0.93)',
    borderColor: '#b07820',
    buttonGradient: 'linear-gradient(135deg, #5a1200 0%, #8b2500 35%, #c84800 70%, #ff9500 100%)',
    buttonText: '#fff0d0',
    inputBg: 'rgba(40, 15, 0, 0.9)',
    particles: ['🏺', '⭐', '🌙', '💫', '🔶', '✨', '🦂', '🐍'],
    glowColor: '#d08020',
  },
  {
    id: 'space',
    name: 'Space World',
    emoji: '🚀',
    description: 'Gravity means nothing here. Alien demon-constructs patrol cosmic temple bridges that stretch into infinite void. One wrong step — you float forever.',
    tagline: 'BEYOND THE STARS',
    primaryColor: '#7b2d8b',
    secondaryColor: '#9b4dab',
    accentColor: '#00e5ff',
    textColor: '#e0d0ff',
    mutedColor: '#9080b0',
    bg: 'radial-gradient(ellipse at 40% 40%, #200040 0%, #0a0018 50%, #020005 100%)',
    cardBg: 'rgba(4, 0, 18, 0.96)',
    borderColor: '#5a1a7a',
    buttonGradient: 'linear-gradient(135deg, #1a0035 0%, #5500a0 40%, #9b00c8 70%, #00e5ff 100%)',
    buttonText: '#e0f0ff',
    inputBg: 'rgba(6, 0, 22, 0.94)',
    particles: ['⭐', '🌟', '💫', '🪐', '🌠', '✨', '👾', '🛸'],
    glowColor: '#00ccee',
  },
  {
    id: 'underwater',
    name: 'Underwater World',
    emoji: '🌊',
    description: 'The ocean\'s pressure crushes all who are unworthy. Glowing deep-sea demons guard sunken relics. Your oxygen is running out — RUN FASTER.',
    tagline: 'DEPTHS OF MYSTERY',
    primaryColor: '#006994',
    secondaryColor: '#0099cc',
    accentColor: '#00e5ff',
    textColor: '#d0f0ff',
    mutedColor: '#80c0d8',
    bg: 'radial-gradient(ellipse at 50% 50%, #003355 0%, #001525 50%, #000810 100%)',
    cardBg: 'rgba(0, 12, 30, 0.94)',
    borderColor: '#006688',
    buttonGradient: 'linear-gradient(135deg, #001a3e 0%, #004488 40%, #0077bb 70%, #00ccff 100%)',
    buttonText: '#d0f5ff',
    inputBg: 'rgba(0, 15, 35, 0.92)',
    particles: ['🐠', '🐙', '🦑', '🐋', '🫧', '✨', '🐡', '🦈'],
    glowColor: '#00bbdd',
  },
  {
    id: 'volcano',
    name: 'Volcano World',
    emoji: '🌋',
    description: 'The earth itself is trying to kill you. Rivers of magma erupt beneath your feet, obsidian demons born of fire give chase. Heaven or hell — your call.',
    tagline: 'BORN IN FIRE',
    primaryColor: '#cc2200',
    secondaryColor: '#ff5500',
    accentColor: '#ff8c00',
    textColor: '#fff0e0',
    mutedColor: '#e08060',
    bg: 'radial-gradient(ellipse at 50% 80%, #aa1800 0%, #550800 40%, #1a0200 100%)',
    cardBg: 'rgba(28, 6, 0, 0.95)',
    borderColor: '#882200',
    buttonGradient: 'linear-gradient(135deg, #400000 0%, #880000 30%, #cc2200 60%, #ff6600 85%, #ffaa00 100%)',
    buttonText: '#fff0d8',
    inputBg: 'rgba(32, 8, 0, 0.92)',
    particles: ['🔥', '💥', '🌋', '🪨', '⚡', '✨', '🫠', '💎'],
    glowColor: '#ff5500',
  },
  {
    id: 'heaven',
    name: 'Heaven World',
    emoji: '☁️',
    description: 'The gates are open — but only for those who earn it. Celestial guardians test your purity atop infinite skybridges of light. One misstep and the clouds part beneath your feet.',
    tagline: 'TOUCHED BY LIGHT',
    primaryColor: '#7cb9e8',
    secondaryColor: '#b0d8f5',
    accentColor: '#ffe566',
    textColor: '#f0f8ff',
    mutedColor: '#a8c8e8',
    bg: 'radial-gradient(ellipse at 50% 20%, #c8e8ff 0%, #7bb8e8 30%, #3a6fa8 70%, #1a3a5c 100%)',
    cardBg: 'rgba(20, 50, 90, 0.88)',
    borderColor: '#5a9fcf',
    buttonGradient: 'linear-gradient(135deg, #1a3a6c 0%, #3a7abf 35%, #7ab8ef 70%, #ffe566 100%)',
    buttonText: '#0a1a2c',
    inputBg: 'rgba(18, 44, 80, 0.88)',
    particles: ['☁️', '✨', '⭐', '🌟', '💫', '🕊️', '🌤️', '🏹'],
    glowColor: '#88ccff',
  },
  {
    id: 'hell',
    name: 'Hell World',
    emoji: '😈',
    description: 'There is no way out. Only deeper. The underworld churns with rivers of brimstone and demons that were cast out for being too vicious. You are not supposed to be here. Keep running.',
    tagline: 'NO EXIT',
    primaryColor: '#c0392b',
    secondaryColor: '#e74c3c',
    accentColor: '#ff6b35',
    textColor: '#ffe8e0',
    mutedColor: '#c0806a',
    bg: 'radial-gradient(ellipse at 50% 100%, #7a0000 0%, #3d0000 40%, #140000 80%, #060000 100%)',
    cardBg: 'rgba(30, 0, 0, 0.96)',
    borderColor: '#6a1515',
    buttonGradient: 'linear-gradient(135deg, #1a0000 0%, #5a0000 30%, #a01010 60%, #e03030 85%, #ff6b35 100%)',
    buttonText: '#ffe0d0',
    inputBg: 'rgba(35, 0, 0, 0.94)',
    particles: ['😈', '🔥', '💀', '⛓️', '🩸', '💔', '🦇', '🌑'],
    glowColor: '#cc2200',
  },
  {
    id: 'flower',
    name: 'Flower World',
    emoji: '🌸',
    description: "The garden was paradise once. Then the blooms turned. Carnivorous vines guard every corridor, pollen demons drift through poisoned meadows, and the sweetest scent you've ever smelled means you're already surrounded.",
    tagline: 'BLOOM OR DOOM',
    primaryColor: '#e91e8c',
    secondaryColor: '#f06292',
    accentColor: '#ff80ab',
    textColor: '#fce4ec',
    mutedColor: '#f48fb1',
    bg: 'radial-gradient(ellipse at 50% 20%, #4a0828 0%, #1a0612 50%, #080308 100%)',
    cardBg: 'rgba(20, 4, 14, 0.93)',
    borderColor: '#8a1040',
    buttonGradient: 'linear-gradient(135deg, #1a0012 0%, #6a0040 35%, #c2185b 70%, #ff80ab 100%)',
    buttonText: '#fff0f4',
    inputBg: 'rgba(24, 4, 16, 0.9)',
    particles: ['🌸', '🌺', '🌼', '🦋', '🌿', '✨', '🌷', '🌹'],
    glowColor: '#e91e8c',
  },
];

export type PaletteCategory = {
  id: string;
  label: string;
  icon: string;
  fields: { type: FieldType; icon: string; label: string }[];
};

export const PALETTE_CATEGORIES: PaletteCategory[] = [
  {
    id: 'text',
    label: 'Text',
    icon: '📝',
    fields: [
      { type: 'text',     icon: '📝', label: 'Short Text' },
      { type: 'textarea', icon: '📄', label: 'Long Text' },
      { type: 'email',    icon: '📧', label: 'Email' },
      { type: 'password', icon: '🔒', label: 'Password' },
      { type: 'url',      icon: '🔗', label: 'URL / Link' },
      { type: 'phone',    icon: '📱', label: 'Phone' },
    ],
  },
  {
    id: 'choice',
    label: 'Choice',
    icon: '☑️',
    fields: [
      { type: 'checkbox', icon: '☑️', label: 'Checkbox' },
      { type: 'radio',    icon: '🔘', label: 'Radio Group' },
      { type: 'select',   icon: '📂', label: 'Dropdown' },
      { type: 'multi_select', icon: '☑️', label: 'Multi-Select' },
    ],
  },
  {
    id: 'numeric',
    label: 'Numeric',
    icon: '🔢',
    fields: [
      { type: 'number',   icon: '🔢', label: 'Number' },
      { type: 'currency', icon: '💰', label: 'Currency' },
      { type: 'range',    icon: '🎚️', label: 'Slider' },
    ],
  },
  {
    id: 'datetime',
    label: 'Date & Time',
    icon: '📅',
    fields: [
      { type: 'date', icon: '📅', label: 'Date' },
      { type: 'time', icon: '⏰', label: 'Time' },
    ],
  },
  {
    id: 'special',
    label: 'Special',
    icon: '⭐',
    fields: [
      { type: 'rating', icon: '⭐', label: 'Star Rating' },
      { type: 'file',   icon: '📎', label: 'File Upload' },
    ],
  },
  {
    id: 'layout',
    label: 'Layout',
    icon: '📐',
    fields: [
      { type: 'section', icon: '📐', label: 'Section Divider' },
      { type: 'page_break', icon: '📄', label: 'Page Break' },
    ],
  },
];

// Flat lookup (for icons etc.)
export const FIELD_TYPES = PALETTE_CATEGORIES.flatMap((c) => c.fields);

// ── Validation presets ──────────────────────────────────────────────────────
export const VALIDATION_PRESETS: { value: ValidationPreset; label: string; pattern: string; hint: string }[] = [
  { value: 'none',          label: 'None',           pattern: '',                         hint: 'No extra validation' },
  { value: 'letters-only',  label: 'Letters Only',   pattern: '^[A-Za-z\\s]+$',           hint: 'Only letters & spaces' },
  { value: 'numbers-only',  label: 'Numbers Only',   pattern: '^[0-9]+$',                 hint: 'Only digits' },
  { value: 'alphanumeric',  label: 'Alphanumeric',   pattern: '^[A-Za-z0-9]+$',           hint: 'Letters and numbers only' },
  { value: 'pan',           label: 'PAN Number',     pattern: '^[A-Z]{5}[0-9]{4}[A-Z]$', hint: 'e.g. ABCDE1234F' },
  { value: 'gst',           label: 'GST Number',     pattern: '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$', hint: 'e.g. 22AAAAA0000A1Z5' },
  { value: 'ifsc',          label: 'IFSC Code',      pattern: '^[A-Z]{4}0[A-Z0-9]{6}$',  hint: 'e.g. HDFC0001234' },
  { value: 'pincode',       label: 'PIN Code',       pattern: '^[0-9]{6}$',               hint: '6-digit postal code' },
  { value: 'custom',        label: 'Custom Regex',   pattern: '',                         hint: 'Enter your own pattern' },
];

// ── Quick-insert Collections ────────────────────────────────────────────────
type PartialField = Omit<Partial<FormField>, 'id'> & { type: FieldType; label: string };

export type Collection = {
  id: string;
  icon: string;
  label: string;
  description: string;
  accentColor: string;
  /** If provided, only show this collection for these purpose ids (plus always 'scratch'). Empty/undefined = universal. */
  purposes?: string[];
  fields: PartialField[];
};

export const COLLECTIONS: Collection[] = [
  {
    id: 'bank',
    icon: '🏦',
    label: 'Bank Details',
    description: 'Account holder, bank, IFSC & more',
    accentColor: '#ffd700',
    purposes: ['onboarding', 'job', 'order', 'scratch'],
    fields: [
      { type: 'section',  label: 'Bank Details', sectionColor: '#ffd700', sectionDescription: 'Secure banking information' },
      { type: 'text',     label: 'Account Holder Name', placeholder: 'Full name as on bank account', required: true, validationPreset: 'letters-only', fieldWidth: 'full' },
      { type: 'text',     label: 'Bank Name', placeholder: 'e.g. HDFC Bank, SBI, ICICI', required: true, fieldWidth: 'half' },
      { type: 'select',   label: 'Account Type', options: ['Savings', 'Current', 'Salary', 'Fixed Deposit'], required: true, fieldWidth: 'half' },
      { type: 'text',     label: 'Account Number', placeholder: 'Enter account number', required: true, minLength: 8, maxLength: 18, validationPreset: 'numbers-only', fieldWidth: 'half' },
      { type: 'text',     label: 'Confirm Account Number', placeholder: 'Re-enter account number', required: true, validationPreset: 'numbers-only', fieldWidth: 'half' },
      { type: 'text',     label: 'IFSC Code', placeholder: 'e.g. HDFC0001234', required: true, maxLength: 11, validationPreset: 'ifsc', fieldWidth: 'half', helperText: '11-character code on your cheque' },
      { type: 'text',     label: 'SWIFT / BIC Code', placeholder: 'e.g. HDFCINBB', required: false, maxLength: 11, fieldWidth: 'half', helperText: 'Required for international transfers' },
    ] as PartialField[],
  },
  {
    id: 'address',
    icon: '🏠',
    label: 'Address Block',
    description: 'Street, city, state, PIN & country',
    accentColor: '#00e5ff',
    purposes: ['onboarding', 'registration', 'order', 'contact', 'job', 'scratch'],
    fields: [
      { type: 'section',  label: 'Address Information', sectionColor: '#00e5ff', sectionDescription: 'Provide full mailing address' },
      { type: 'text',     label: 'Address Line 1', placeholder: 'House / Flat No., Street, Area', required: true, fieldWidth: 'full' },
      { type: 'text',     label: 'Address Line 2', placeholder: 'Landmark, Colony (optional)', required: false, fieldWidth: 'full' },
      { type: 'text',     label: 'City', placeholder: 'Enter city', required: true, validationPreset: 'letters-only', fieldWidth: 'half' },
      { type: 'text',     label: 'State / Province', placeholder: 'Enter state', required: true, validationPreset: 'letters-only', fieldWidth: 'half' },
      { type: 'text',     label: 'PIN / Postal Code', placeholder: 'e.g. 400001', required: true, validationPreset: 'pincode', maxLength: 10, fieldWidth: 'half' },
      { type: 'select',   label: 'Country', required: true, fieldWidth: 'half', options: ['India', 'United States', 'United Kingdom', 'Canada', 'Australia', 'Germany', 'France', 'UAE', 'Singapore', 'Other'] },
    ] as PartialField[],
  },
  {
    id: 'tax',
    icon: '📋',
    label: 'Tax Information',
    description: 'PAN, GST, income & filing details',
    accentColor: '#ff8c00',
    purposes: ['job', 'order', 'scratch'],
    fields: [
      { type: 'section',  label: 'Tax Information', sectionColor: '#ff8c00', sectionDescription: 'Financial & tax details for compliance' },
      { type: 'text',     label: 'PAN Number', placeholder: 'e.g. ABCDE1234F', required: true, maxLength: 10, validationPreset: 'pan', fieldWidth: 'half', helperText: 'Permanent Account Number (10 characters)' },
      { type: 'select',   label: 'Taxpayer Category', required: true, fieldWidth: 'half', options: ['Individual', 'HUF', 'Partnership Firm', 'Private Limited', 'Public Limited', 'Trust', 'NGO'] },
      { type: 'text',     label: 'GST Number', placeholder: 'e.g. 22AAAAA0000A1Z5', required: false, maxLength: 15, validationPreset: 'gst', fieldWidth: 'half', helperText: 'Leave blank if not GST registered' },
      { type: 'select',   label: 'Financial Year', required: true, fieldWidth: 'half', options: ['2025-26', '2024-25', '2023-24', '2022-23', '2021-22'] },
      { type: 'currency', label: 'Annual Income', placeholder: '0.00', required: true, prefix: '₹', fieldWidth: 'half' },
      { type: 'radio',    label: 'Tax Filing Status', required: true, fieldWidth: 'half', options: ['Filed', 'Pending', 'Exempt', 'Not Applicable'] },
      { type: 'select',   label: 'Income Tax Slab', required: false, fieldWidth: 'full', options: ['0% (Up to ₹3L)', '5% (₹3L – ₹7L)', '10% (₹7L – ₹10L)', '15% (₹10L – ₹12L)', '20% (₹12L – ₹15L)', '30% (Above ₹15L)'], helperText: 'As per new tax regime 2024-25' },
      { type: 'checkbox', label: 'I confirm that the above tax information is accurate and complete', required: true, fieldWidth: 'full' },
    ] as PartialField[],
  },
  {
    id: 'vitals',
    icon: '💊',
    label: 'Vital Signs',
    description: 'Height, weight, BP, pulse, temp',
    accentColor: '#ef9a9a',
    purposes: ['health'],
    fields: [
      { type: 'section', label: 'Vital Signs', sectionColor: '#e53935', sectionDescription: 'Current physical measurements' },
      { type: 'number',  label: 'Height (cm)', placeholder: 'e.g. 170', required: false, min: 50, max: 250, fieldWidth: 'half' },
      { type: 'number',  label: 'Weight (kg)', placeholder: 'e.g. 70', required: false, min: 1, max: 300, fieldWidth: 'half' },
      { type: 'text',    label: 'Blood Pressure', placeholder: 'e.g. 120/80 mmHg', required: false, fieldWidth: 'half' },
      { type: 'number',  label: 'Pulse Rate (bpm)', placeholder: 'e.g. 72', required: false, min: 30, max: 200, fieldWidth: 'half' },
      { type: 'number',  label: 'Temperature (°F)', placeholder: 'e.g. 98.6', required: false, fieldWidth: 'half', min: 90, max: 110 },
      { type: 'select',  label: 'Oxygen Saturation (SpO2)', required: false, fieldWidth: 'half', options: ['100%', '99%', '98%', '97%', '96%', '95%', 'Below 95%'] },
    ] as PartialField[],
  },
  {
    id: 'medical_history',
    icon: '🩺',
    label: 'Medical History',
    description: 'Conditions, allergies, medications',
    accentColor: '#ef5350',
    purposes: ['health'],
    fields: [
      { type: 'section',  label: 'Medical History', sectionColor: '#c62828', sectionDescription: 'Previous and existing health conditions' },
      { type: 'textarea', label: 'Known Allergies', placeholder: 'Food, medication, environmental — list all', required: false },
      { type: 'textarea', label: 'Current Medications', placeholder: 'Include name, dosage and frequency', required: false },
      { type: 'textarea', label: 'Pre-existing Conditions', placeholder: 'Diabetes, hypertension, asthma, etc.', required: false },
      { type: 'checkbox', label: 'Any history of surgery or hospitalization?', required: false, fieldWidth: 'half' },
      { type: 'checkbox', label: 'Family history of hereditary conditions?', required: false, fieldWidth: 'half' },
      { type: 'textarea', label: 'Additional Medical Notes', placeholder: 'Anything else your doctor should know...', required: false },
    ] as PartialField[],
  },
  {
    id: 'emergency_contact',
    icon: '🚨',
    label: 'Emergency Contact',
    description: 'Name, relation, phone for emergencies',
    accentColor: '#ff5252',
    purposes: ['health', 'registration', 'onboarding', 'scratch'],
    fields: [
      { type: 'section', label: 'Emergency Contact', sectionColor: '#b71c1c', sectionDescription: 'Who to contact in case of emergency' },
      { type: 'text',    label: 'Contact Name', placeholder: 'Full name', required: true, validationPreset: 'letters-only', fieldWidth: 'half' },
      { type: 'text',    label: 'Relationship', placeholder: 'e.g. Spouse, Parent, Sibling', required: true, fieldWidth: 'half' },
      { type: 'phone',   label: 'Phone Number', placeholder: '+91 00000 00000', required: true, fieldWidth: 'half' },
      { type: 'phone',   label: 'Alternate Phone', placeholder: '+91 00000 00000', required: false, fieldWidth: 'half' },
    ] as PartialField[],
  },
  {
    id: 'lifestyle',
    icon: '🏃',
    label: 'Lifestyle & Habits',
    description: 'Diet, exercise, sleep, substance use',
    accentColor: '#a5d6a7',
    purposes: ['health'],
    fields: [
      { type: 'section', label: 'Lifestyle & Habits', sectionColor: '#2e7d32', sectionDescription: 'Daily habits affecting your health' },
      { type: 'radio',   label: 'Dietary Preference', required: false, fieldWidth: 'half', options: ['Vegetarian', 'Vegan', 'Non-Vegetarian', 'Eggetarian', 'Other'] },
      { type: 'select',  label: 'Exercise Frequency', required: false, fieldWidth: 'half', options: ['Daily', '4–5 times/week', '2–3 times/week', 'Once a week', 'Rarely', 'Never'] },
      { type: 'select',  label: 'Average Sleep (hours/night)', required: false, fieldWidth: 'half', options: ['Less than 5', '5–6', '6–7', '7–8', 'More than 8'] },
      { type: 'radio',   label: 'Smoking Status', required: false, fieldWidth: 'half', options: ['Non-smoker', 'Ex-smoker', 'Occasional', 'Regular'] },
      { type: 'radio',   label: 'Alcohol Consumption', required: false, fieldWidth: 'half', options: ['Never', 'Rarely', 'Socially', 'Weekly', 'Daily'] },
      { type: 'select',  label: 'Stress Level', required: false, fieldWidth: 'half', options: ['Very Low', 'Low', 'Moderate', 'High', 'Very High'] },
    ] as PartialField[],
  },
  {
    id: 'social_links',
    icon: '🌐',
    label: 'Social Profiles',
    description: 'LinkedIn, GitHub, Twitter & more',
    accentColor: '#64b5f6',
    purposes: ['job', 'onboarding', 'scratch'],
    fields: [
      { type: 'section', label: 'Social Profiles', sectionColor: '#1565c0', sectionDescription: 'Professional & social presence' },
      { type: 'url',     label: 'LinkedIn Profile', placeholder: 'https://linkedin.com/in/...', required: false, fieldWidth: 'half' },
      { type: 'url',     label: 'GitHub Profile', placeholder: 'https://github.com/...', required: false, fieldWidth: 'half' },
      { type: 'url',     label: 'Portfolio / Website', placeholder: 'https://...', required: false, fieldWidth: 'half' },
      { type: 'url',     label: 'Twitter / X Profile', placeholder: 'https://x.com/...', required: false, fieldWidth: 'half' },
    ] as PartialField[],
  },
];
